apiVersion: v1
kind: ConfigMap
metadata:
  name: farmhand-api-config
data:
  FRONTEND_URL: "https://staging.farmhand.witchscrow.com"
  RUST_LOG: "api=debug,db=debug,queue=debug,tower_http=debug,axum::rejection=trace"
  FFMPEG_LOCATION: "/opt/homebrew/bin/ffmpeg" # TODO: Make this is the right path for docker context
  TWITCH_REDIRECT_URI: "https://staging.api.farmhand.witchscrow.com/auth/twitch/callback"
  LOG_LEVEL: "api=debug"
  STORAGE: "videos/staging" # TODO: Make this dynamic per environment
  UPLOAD_BUCKET: "farmhand"
