apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmhand-api
spec:
  selector:
    matchLabels:
      app: farmhand-api
  template:
    metadata:
      labels:
        app: farmhand-api
    spec:
      containers:
        - name: farmhand-api
          image: api
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: farmhand-api-config
            - secretRef:
                name: urdar-default-credentials
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: urdar-default-credentials
                  key: uri
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
