apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmhand-api
spec:
  selector:
    matchLabels:
      app: farmhand-api
  template:
    metadata:
      labels:
        app: farmhand-api
    spec:
      containers:
        - name: farmhand-api
          image: api
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: farmhand-api-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: farmhand-db
                  key: uri
            - name: TWITCH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: farmhand-twitch-credentials
                  key: client-id
            - name: TWITCH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: farmhand-twitch-credentials
                  key: client-secret
            - name: R2_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: farmhand-cloudflare-credentials
                  key: account-id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: farmhand-cloudflare-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: farmhand-cloudflare-credentials
                  key: secret-access-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: farmhand-jwt
                  key: secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
