apiVersion: v1
kind: ConfigMap
metadata:
  name: farmhand-queue-config
data:
  RUST_LOG: "api=debug,db=debug,queue=debug,tower_http=debug,axum::rejection=trace"
  STORAGE: "videos/staging"
  UPLOAD_BUCKET: "farmhand"
