apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmhand-queue
spec:
  selector:
    matchLabels:
      app: farmhand-queue
  template:
    metadata:
      labels:
        app: farmhand-queue
    spec:
      containers:
        - name: farmhand-queue
          image: queue
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: farmhand-queue-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: farmhand-db
                  key: uri
            - name: R2_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: farmhand-cloudflare-credentials
                  key: account-id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: farmhand-cloudflare-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: farmhand-cloudflare-credentials
                  key: secret-access-key
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
