[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = { version = "0.5", features = ["password-hash"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "chrono"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
