name: build queue

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v2
      - name: build
        run: just build-queue
