name: build api

on:
  push:
    branches: [main]
    paths:
      - "packages/api/**"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: [main]
    paths:
      - "packages/api/**"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: /usr/local/cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo target directory
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Install dependencies
        run: cargo build -p api --workspace --release
