apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/api

images:
  - name: api
    newName: placeholder
    newTag: placeholder

labels:
  - includeSelectors: true
    pairs:
      environment: staging
