apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
nameSuffix: -staging

resources:
  - ../../base/api
  - ../../base/ui
  - ingress.yaml

images:
  - name: api
  - name: ui

labels:
  - includeSelectors: true
    pairs:
      environment: staging
